### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by R-Tsukada** [R-Tsukada/football-calendar#5]

**Comment by R-Tsukada** [comment]
DB設計図

<img width="827" alt="er_drawio_-_diagrams_net" src="https://user-images.githubusercontent.com/62058863/157805719-0dbcddc8-a920-4eee-b234-26be6556e367.png">

**Comment by kfukai23** [comment]
- Standing の FK が typo していそうです〜
- Match.season はその試合がどのシーズンに属するか？の情報が入るかと思いますが、文字列で`'21-22'`などと入るイメージでしょうか？それでも良いとは思いますが、Match の集計では必ず現在の season だけに絞り込む必要があるのと、その集計が頻繁に発生しそうなので不便にならないかがちょっと心配です。必要になったら別のエンティティに分けることも頭の片隅に置いとくといいかもです。本来エンティティとしては試合そのものとは別モノですしね。
- Team.league は league_id になるかと思います
- ペーパープロトタイプを見ると1つの Team が複数の大会に参加していたらそれらすべてを日程表に表示する想定に見えます。例えば[このページ](https://bootcamp.fjord.jp/products/11075#-37)では Arsenal の日程としてプレミアリーグと FA Cup の両方を表示していますね。この場合、大会そのものの情報はすべて League に持つ想定でしょうか？だとすると League:Team は1対多ではなく多対多にしている必要がありそうです
- ペーパープロトタイプだと[ユーザーが複数のチームをウォッチする仕組みになっていて](https://bootcamp.fjord.jp/products/11075#-38)、その内訳として「応援しているチーム」と「ライバルチーム」を区別しているようです。DB 上、その区別はどこで持つイメージですかね？:eyes:
- ペーパープロトタイプ見る限りスタジアム名を表示する画面がなさそうでしたが、Team.home_stadium_name は必要ですか？（見落としていたらすみません）

**Comment by kfukai23** [comment]
あ、あと Favorite から伸びる鳥足の向きが意図と違ってそうです！（「多」として分岐している方は、User / Team 側ではなく Favorite 側にくるはず）

**Comment by R-Tsukada** [comment]
DB設計図（修正版）
<img width="719" alt="er_drawio_-_diagrams_net" src="https://user-images.githubusercontent.com/62058863/159163976-48d17b85-e690-4446-b35e-0c2488849b07.png">


> ・Standing の FK が typo していそうです〜
・Team.league は league_id になるかと思います

すみません！修正しました。

> Match.season はその試合がどのシーズンに属するか？の情報が入るかと思いますが、文字列で'21-22'などと入るイメージでしょうか？

外部APIの関係上、'2021'という形式になります。
実装を進めていって絞り込み・集計がやりにくそうであれば、エンティティを分けるようにします。
このようなことを考えていませんでした。ありがとうございます🙇‍♂️

> ペーパープロトタイプを見ると1つの Team が複数の大会に参加していたらそれらすべてを日程表に表示する想定に見えます。例えば[このページ](https://bootcamp.fjord.jp/products/11075#-37)では Arsenal の日程としてプレミアリーグと FA Cup の両方を表示していますね。この場合、大会そのものの情報はすべて League に持つ想定でしょうか？だとすると League:Team は1対多ではなく多対多にしている必要がありそうです

こちらカラムを追加するのを忘れていました🙇‍♂️
外部APIでLeague[name]で試合の大会名を取得できます。なので大会に関するモデルは作らず、Matchのカラムに大会名を追加するつもりです。カラム名は「competition」です。

<img width="534" alt="Dashboard___Api-Sports___soccer___tester_🔊" src="https://user-images.githubusercontent.com/62058863/159163786-b91a68ca-9b35-4294-a45b-c97dbfab2887.png">


> ペーパープロトタイプだと[ユーザーが複数のチームをウォッチする仕組みになっていて](https://bootcamp.fjord.jp/products/11075#-38)、その内訳として「応援しているチーム」と「ライバルチーム」を区別しているようです。DB 上、その区別はどこで持つイメージですかね？👀

これはFavoriteの先頭に「応援しているチーム」が来るようにしようと思っていました。ただ難しそうなので変更しました。
「応援しているチーム」を「Favorite」、「ライバルチーム」を「Competitor」というモデルに分けようと思っています。「Favorite」、「Competitor」どちらもユーザーフォロー機能のような方法にするつもりです。

> ペーパープロトタイプ見る限りスタジアム名を表示する画面がなさそうでしたが、Team.home_stadium_name は必要ですか？（見落としていたらすみません）

こちらは削除するのを忘れていました🙇‍♂️
ペーパープロトタイプ提出後にホームスタジアム名を表記しようと考えていたのですが、必要性がなさそうなのでやめました。

**Comment by kfukai23** [comment]
修正・コメントありがとうございます！
Favorite と User は 1:1 になるはずなので、User に FK として team_id を持つ選択肢もあると思いますので検討してみてください！（このままでもいいとは思います:ok_hand:）サービス上「応援しているチーム」を登録せずに利用することがあるなら User.team_id は nullable にしないといけませんが、null が入るのをなるべく避けたい！ということなら分けておくのも手です。その場合は Favorites テーブルに対して user_id での unique 制約を忘れずにかけましょう〜

追加でもう一つ思いついたので教えてください:bow: Standing って順位表の各行が入るようなイメージですかね？（赤枠で囲った部分を1レコードとして持つ？）

![スクリーンショット 2022-03-21 12 33 48](https://user-images.githubusercontent.com/36021748/159201984-27075fe8-d70f-4806-9c46-003e0152c986.png)
※ https://www.premierleague.com/tables より

試合が行われるたびに順位表の情報は変わりますが、その都度レコードを更新するのでしょうか？
順位表で表示すべき情報って、勝ち点にしても、得失点差にしても、これまでに消化された試合のデータを集計したものだと思うので、表示のたびに Match を集計する形になるのでは？と思っています。
もしかすると、API には順位表を返してくれるものもあってそれを利用する想定ですかね？それなら都度 API を叩いてそのレスポンスを使うだけなので色々と楽そうで良いなーと思いますが、その場合もやはり DB に順位表を持つ必要はないのでは？と思いました。
後出しですみませんが教えてください〜:pray:

**Comment by R-Tsukada** [comment]
> Favorite と User は 1:1 になるはずなので、User に FK として team_id を持つ選択肢もあると思いますので検討してみてください！（このままでもいいとは思います👌）

その方法は思いついていませんでした！
とりあえずは現状のまま実装していきたいと思いますが、必要に応じて検討していきます。

> サービス上「応援しているチーム」を登録せずに利用することがあるなら

「応援しているチーム」を登録するのは必須にしようと思っています。「応援しているチーム」がある人をサービスのターゲットにするつもりです。

> もしかすると、API には順位表を返してくれるものもあってそれを利用する想定ですかね？それなら都度 API を叩いてそのレスポンスを使うだけなので色々と楽そうで良いなーと思いますが、その場合もやはり DB に順位表を持つ必要はないのでは？と思いました。

APIが順位を返してくれます！
DBを使わずにレスポンスを返す方法があるんですね💡DBに保存しなくても対応できるのであれば、そのようにしたいと思います。いまは実装方法がわからないので調べてみます。

**Comment by kfukai23** [comment]
> DBを使わずにレスポンスを返す方法があるんですね💡DBに保存しなくても対応できるのであれば、そのようにしたいと思います。いまは実装方法がわからないので調べてみます。

はい、ユーザが画面を開いたら、都度サーバ側で API を叩いて、他の情報と組み合わせて使う感じですね。SPA で作るなら、クライアント側で直接 API を呼び出す実装にするのも選択肢の一つかなぁと思います。
API レスポンスを DB に持ってそれを見る形にすると、頻繁にレコードを更新しておかないと、すぐに情報が古くなってしまいますよね。その更新タイミングを適切に設定するのが結構難しい気がしました。

一旦 DB ありで進めて、やっぱり API 都度呼び出しでよいとなったら捨てるのでも良いんじゃないかなーと思います。

**Comment by R-Tsukada** [comment]
返信遅れてしまい申し訳ありません🙏お返事するのを失念していました🙇‍♂️

> 一旦 DB ありで進めて、やっぱり API 都度呼び出しでよいとなったら捨てるのでも良いんじゃないかなーと思います。

まずはDBありで進めていきたいと思います。
実装を進めていきながら、必要性を感じたら修正するようにしたいと思います🙏
